#!/bin/env ruby
# rubocop:disable Style/GlobalVars

# Supported Extensions:
# zip, rar, 7z, tar, tar.xz, tar.gz, tar.bz2

require 'securerandom'
require 'fileutils'
require 'optparse'

class Modes
  LIST    = 0
  EXTRACT = 1
  CREATE  = 2
end

$options = {}

optionparser = OptionParser.new do |opt|
  opt.on('-w', '--workdir WORKDIR', 'Working dir') { |x| $options[:workdir] = x }
  opt.on('-o', '--output FILENAME', 'Output filename (optional)') { |x| $options[:filename] = x }
  opt.on('-p', '--password PASSWORD', 'Archive Password (optional)') { |x| $options[:password] = x }

  opt.on('-m', '--mode MODE', 'Mode (l=list, x=extract, c=create)') do |mode|
    $options[:mode] = case mode
                      when 'l'
                        Modes::LIST
                      when 'x'
                        Modes::EXTRACT
                      when 'c'
                        Modes::CREATE
                      end
  end
end

optionparser.parse!

raise OptionParser::MissingArgument if ARGV.empty?
raise OptionParser::InvalidArgument if $options[:mode].nil?
raise OptionParser::MissingArgument if $options[:workdir].nil?

$arg = ARGV[0]

$tmpname = SecureRandom.uuid
Dir.chdir $options[:workdir]

def get_mimetype(filename)
  `file -b --mime-type '#{filename}'`.chomp!
end

def check_extracted_folder(name)
  children = Dir.children $tmpname

  if children.length == 1
    childrenpath = File.join $tmpname, children.first
    FileUtils.mv childrenpath, Dir.getwd, force: true
    FileUtils.rmdir $tmpname
    FileUtils.rmdir name if Dir.exist?(name) && Dir.empty?(name)
  else
    FileUtils.mv $tmpname, name
  end

  return unless name.end_with? '.tar'

  FileUtils.mv name, name[..-5]
end

def list_archive
  mime = get_mimetype $arg

  case mime
  when 'application/zip'
    system "unzip -l '#{$arg}'"
  when 'application/x-rar'
    system "unrar l '#{$arg}'"
  when 'application/x-7z-compressed'
    system "7z l '#{$arg}'"
  when 'application/x-tar', 'application/x-xz', 'application/x-gz',
       'application/x-bz2', 'application/gzip', 'application/x-bzip2'
    system "tar tf '#{$arg}' | tree --fromfile -C"
  else
    raise "Cannot list #{$arg} files #{mime}"
  end
end

def extract_archive
  # https://www.cyberciti.biz/faq/howto-extract-tar-file-to-specific-directory-on-unixlinux/
  name = File.basename $arg, File.extname($arg)
  mime = get_mimetype $arg

  case mime
  when 'application/zip'
    system "unzip -o -d #{$tmpname} '#{$arg}'"
  when 'application/x-rar'
    FileUtils.mkdir $tmpname
    system "unrar x '#{$arg}' #{$tmpname}"
  when 'application/x-7z-compressed'
    system "7z x '#{$arg}' -o#{$tmpname}"
  when 'application/x-tar', 'application/x-xz'
    FileUtils.mkdir $tmpname
    system "tar xvf '#{$arg}' -C#{$tmpname}"
  when 'application/x-gz', 'application/gzip'
    FileUtils.mkdir $tmpname
    system "tar zxvf '#{$arg}' -C#{$tmpname}"
  when 'application/x-bz2', 'application/x-bzip2'
    FileUtils.mkdir $tmpname
    system "tar jxvf '#{$arg}' -C#{$tmpname}"
  else
    raise "Cannot extract #{$arg} files (#{mime})"
  end

  check_extracted_folder name
end

def create_archive
  filename = $options[:filename]
  raise OptionParser::MissingArgument if filename.nil? || filename.empty?

  password = $options[:password]
  ext = File.extname filename

  case ext
  when '.zip'
    password = "-P #{password}" unless password.nil?
    system "zip -r #{password} #{filename} #{$arg}"
  when '.rar'
    password = "-hp#{password}" unless password.nil?
    system "rar #{password} a -r '#{filename}' #{$arg}"
  when '.7z'
    password = "-P#{password}" unless password.nil?
    system "7z #{password} a -r '#{filename}' #{$arg}"
  when '.tar'
    raise '.tar archive doesn\'t support passwords' unless password.nil?

    system "tar cvf '#{filename}' #{$arg}"
  when '.xz'
    raise '.tar.xz archive doesn\'t support passwords' unless password.nil?

    system "tar cvfJ '#{filename}' #{$arg}"
  when '.gz'
    raise '.tar.gz archive doesn\'t support passwords' unless password.nil?

    system "tar cvfz '#{filename}' #{$arg}"
  when '.bz2'
    raise '.tar.bz2 archive doesn\'t support passwords' unless password.nil?

    system "tar cvfj '#{filename}' #{$arg}"
  else
    raise "Cannot create archive #{$arg} (#{ext})"
  end
end

case $options[:mode]
when Modes::LIST
  list_archive
when Modes::EXTRACT
  extract_archive
when Modes::CREATE
  create_archive
end

# rubocop:enable Style/GlobalVars
