#!/bin/sh

files=$(echo "$1" | awk -v path="$2" '{
    while(match($0, /"([^"]+)"/)) {
        f = substr($0, RSTART + 1, RLENGTH - 2);
        print "file://"path"/"f;
        $0 = substr($0, RSTART + RLENGTH);
    }
}')

if [ -n "$files" ]; then
    echo "$files" | xclip -i -selection clipboard -t text/uri-list > /dev/null
    echo "$(echo "$files" | wc -l) files(s) copied to clipboard"
fi
